[package]
name = "Crypt"
version = "0.1.0"
authors = ["Tiqur <Tiqur7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
base64 = "0.13.0"
libdeflater = "0.7.1"